CREATE SEQUENCE IF NOT EXISTS "MY_OWN_SEQ" 
MINVALUE 1 
MAXVALUE 999999999 
INCREMENT BY 1 
START WITH 2 
NOCACHE 
NOCYCLE;

CREATE TABLE IF NOT EXISTS users(
	id VARCHAR(50)  DEFAULT nextval('MY_OWN_SEQ') PRIMARY KEY ,
	name VARCHAR(50),
	email VARCHAR(80),
	username VARCHAR(80),
	password VARCHAR(80)
	);
CREATE TABLE IF NOT EXISTS role (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS users_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES role(id) ON DELETE CASCADE
);